library(tidyverse)
install.packages("car")
library(car)
pysch <- Hospital_Database %>% filter(Service =="0")
general <- Hospital_Database %>% filter(Service =="1")
cor(pysch$Service,y, method = "pearson")
cor(x,y, method = "pearson")
model <- lm(`Total Expenditure` ~ Personnel ,data = Hospital_Database)
summary(model)
model2 <- lm(`Total Expenditure` ~ Personnel + Beds + Admissions + `Outpatient Visits` + Births ,data = Hospital_Database)
summary(model2)
model2 <- lm(`Total Expenditure` ~ Personnel +Admissions +Births ,data = Hospital_Database)
summary(model2)
##Checking for collinearity 
model2 <- lm(`Total Expenditure` ~ Personnel + Admissions,data = Hospital_Database)
summary(model2)
model2 <- lm(`Total Expenditure` ~ Personnel + Births ,data = Hospital_Database)
summary(model2)
model2 <- lm(`Total Expenditure` ~ Admissions +Births ,data = Hospital_Database)
summary(model2)
vif(model2)
